export default {
  Mainnet: {
    JourneyFactory: {},
    Journey: {}
  },
  Rinkeby: {
    JourneyFactory: {
      address: '0xed7a5352026df78747290e04da13cb2396df840b',
      ABI: [{"constant":false,"inputs":[{"name":"_name","type":"string"},{"name":"_description","type":"string"},{"name":"_salt","type":"uint256"},{"name":"_reward","type":"uint256"},{"name":"_secrets","type":"bytes32[]"},{"name":"_lats","type":"uint256[]"},{"name":"_longs","type":"uint256[]"},{"name":"_hints","type":"string[]"}],"name":"createNewAdventure","outputs":[{"name":"","type":"address"}],"payable":true,"stateMutability":"payable","type":"function"},{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"adventures","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"getAdventures","outputs":[{"name":"","type":"address[]"}],"payable":false,"stateMutability":"view","type":"function"}]
    },
    Journey: {
      ABI: [{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"caches","outputs":[{"name":"secret","type":"bytes32"},{"name":"lat","type":"uint256"},{"name":"long","type":"uint256"},{"name":"hint","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_secrets","type":"uint256[]"}],"name":"submitProof","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_claim","type":"bytes32"}],"name":"submitClaim","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"proofs","outputs":[{"name":"prover","type":"address"},{"name":"proof","type":"bytes32"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"claims","outputs":[{"name":"claimer","type":"address"},{"name":"claim","type":"bytes32"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"factory","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"getDetails","outputs":[{"name":"","type":"string"},{"name":"","type":"address"},{"name":"","type":"string"},{"name":"","type":"uint256"},{"components":[{"name":"secret","type":"bytes32"},{"name":"lat","type":"uint256"},{"name":"long","type":"uint256"},{"name":"hint","type":"string"}],"name":"","type":"tuple[]"},{"name":"","type":"bool"},{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[{"name":"_creator","type":"address"},{"name":"_name","type":"string"},{"name":"_description","type":"string"},{"name":"_salt","type":"uint256"},{"name":"_reward","type":"uint256"},{"name":"_secrets","type":"bytes32[]"},{"name":"_lats","type":"uint256[]"},{"name":"_longs","type":"uint256[]"},{"name":"_hints","type":"string[]"}],"payable":true,"stateMutability":"payable","type":"constructor"},{"payable":true,"stateMutability":"payable","type":"fallback"},{"anonymous":false,"inputs":[],"name":"ProofVerified","type":"event"}]
    }
  }
}
